config/routes.rb
Task4::Application.routes.draw do
  resources :images
  root :to => "images#index"

end

app/models/image.rb
class Image < ActiveRecord::Base
  #attr_accessor :image_name_file_name
  #attr_accessor :image_name_content_type
  #attr_accessor :image_name_file_size
  #attr_accessor :image_name_updated_at
  
  #has_attached_file :image_name, styles: { large:"600x300",  medium: "400x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  #validates_attachment_content_type :image_name, content_type: /\Aimage\/.*\Z/
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "200x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  validates_attachment_size :avatar, :in => 0.kilobytes..201.kilobytes, :message => 'Max 200 kb'  
 # validates_attachment_size :avatar, :less_than => 201.kilobytes, :message => lambda { I18n.t('invalid_image_size') }  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
    @images =Image.all
  end

  def new
    @image = Image.new
  end

  def edit
  end
  
  def create
    @image = Image.new(image_params)
    if @image.save
      flash[:notice] = "Success Add Record"
      redirect_to action: 'index'
    else
      flash[:error] = "data not valid"
      render 'new'
    end
  end
  def edit
    @image = Image.find_by_id(params[:id])
    
  end
  
  def update
    @image = Image.find_by_id(params[:id])
    
    if @image.update(image_params)

      flash[:notice] = "Success Add Records"
      redirect_to action: 'index'
    else
      flash[:error] = "data not valid"
      render 'edit'
    end
  end
  
  def destroy
    @image = Image.find_by_id(params[:id])
    if @image.destroy
      flash[:notice] = "Success Delete a Record"
      redirect_to action: 'index'
      #redirect_to articles_url
    else
      flash[:notice] = "fails delete a record"
      redirect_to action: 'index'
    end
  end

  private
  
  # Use strong_parameters for attribute whitelisting
  # Be sure to update your create() and update() controller methods.
  
  def image_params
    params.require(:image).permit(:title, :avatar)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/images/edit.html.erb
<%= form_for @image, :html => { :multipart => true} do |f| %>
<%= f.label :title%>
<%= f.text_field :title%>
<br />
<%= f.label :image_name%>
<%= f.file_field :avatar%>
<br />
<%= f.submit :submit %>
<% end %>

<div>
	<%= link_to "back to index", images_path %>
</div>

app/views/images/index.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,
    initial-scale=1.0">
    <title><%= content_for?(:title) ?
    yield(:title) : "Myapp" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head> 
  <body >
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
           	<% @images.each do |image| %>				
			  <div class="col-sm-3 col-md-2">
			    <div class="thumbnail">
			    	<%=link_to image_tag(image.avatar.url(:thumb)), image.avatar.url(:original), :popup=>['original_image', 'height=400,width=200'] %>
			    	
				
			      <div class="caption">
			       	<%= image.title %>
			        <p>
						<span><%= link_to 'edit', edit_image_path(image.id)%></span>
						<span>|</span>
						<span><%= link_to 'delete', image_path(image.id), method: "DELETE", data: {confirm: 'Delete this data ?'} %></span>
					</p>
			       </div>
			    </div>
			  </div>			
				<% end %>
              <%= yield %>
              
          </div>
          <footer>

          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/images/new.html.erb
<%= form_for @image, :url => images_path, :html => { :multipart => true} do |f| %>
<%= f.label :title%>
<%= f.text_field :title%>
<br />
<%= f.label :image_name%>
<%= f.file_field :avatar%>
<br />
<%= f.submit :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Task4</title>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>